[[mgr.prepend_keymap]]
on = ["g", "o"]
run = 'shell --block "win_start \"$0\""'
desc = "win_start"

[[mgr.prepend_keymap]]
on = ["T", "c"]
run = 'shell --block "tar --zstd -cPf \"$0.tar.zst\" \"$0\""'
desc = "tar -czf"

[[mgr.prepend_keymap]]
on = ["T", "x"]
run = 'shell --block "tar --zstd -xPf \"$0\""'
desc = "tar -xzf"

[[mgr.prepend_keymap]]
on = ["T", "C"]
run = 'shell --block "sudo tar --zstd -cPf \"$0.tar.zst\" \"$0\""'
desc = "sudo tar -czf"

[[mgr.prepend_keymap]]
on = ["T", "X"]
run = 'shell --block "sudo tar --zstd -xPf \"$0\""'
desc = "sudo tar -xzf"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd /mnt/d/dyhtool/wsl/"
desc = "Cd to /mnt/d/dyhtool/wsl/"

[[mgr.prepend_keymap]]
on = ["b"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = ["B", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = ["B", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# sudo cp/mv
[[mgr.append_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

# sudo cp/mv --force
[[mgr.append_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

# sudo mv
[[mgr.append_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

# sudo ln -s (absolute-path)
[[mgr.append_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.append_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

# sudo ln
[[mgr.append_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

# sudo touch/mkdir
[[mgr.append_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

# sudo trash
[[mgr.append_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

# sudo delete
[[mgr.append_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"
